cache: packages
sudo: false

matrix:
  include:
    - language: python
      python:
        - "3.6"
        - "3.7"
        - "3.7-dev"
        - "3.8"
        - "3.8-dev"
      install:
        - sudo pip install -U distutils-pytest setuptools
        - sudo python setup.py build
        - sudo python setup.py install
      script:
        - sudo pip install git+https://github.com/BenjaminIsaac0111/humanleague.git@Development#egg=humanleague
        - sudo pip install git+https://github.com/BenjaminIsaac0111/UKCensusAPI.git@Development#egg=ukcensusapi
        - sudo pip install git+https://github.com/nismod/household_microsynth.git@Development#egg=household_microsynth
        - sudo pip install git+https://github.com/nismod/ukpopulation.git@Development#egg=ukpopulation
        - python setup.py test

warnings_are_errors: false