cache: packages
sudo: false

matrix:
  include:
    - language: python
      python: 3.7
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py test

  allow_failures:
    - r: oldrel
    - r: release
    - r: devel

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
