cache: packages
sudo: false

matrix:
  include:
    - language: python
      python: 3.8-dev
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - # pip install -r requirements.txt
      script:
        - # python setup.py test
        
    - language: python
      python: 3.7
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - # pip install -r requirements.txt
      script:
        - # python setup.py test

    - language: python
      python: 3.5
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - # pip install -r requirements.txt
      script:
        - # python setup.py test

    - language: python
      python: 3.6
      env:
        - NOMIS_API_KEY=DUMMY
      install:
        - # pip install -r requirements.txt
      script:
        - # python setup.py test

  allow_failures:
    - r: oldrel
    - r: release
    - r: devel

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
